# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10e7fd6df6a80ed3293d8367d86891af330a5f0eee759519081b11ef610150ddf0082e7ac1adf0defe9389dc46b893f454a9538c8383ab7e0fe0e85723c673ce

test:
  secret_key_base: c0b7f2b29daa0e1d0b4ddebecefea0cfdc052778239756cde5bf32b06f182f3c80b80b6a438a6b10735f2e22ec3377f15672a707bf3ed0b2f70b5cb2d13a6d0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


#Stripe
development:
  stripe_publishable_key: pk_test_fm1DXLCkPnRYuFfPmBweEqd9
  stripe_secret_key:      sk_test_OgkHZeQNYO6i7GbLEz5uHnjS

production:
  stripe_publishable_key: ENV['stripe_publishable_key']
  stripe_secret_key:      ENV['stripe_secret_key']

